version: '3.4'
services:
  ### ROOT CONFIG CONTAINER -- SHELL ###
  root-config:
    container_name: root
    build:
        context: ./root-config
        dockerfile: ./DockerFile
    ports:
        - 8081:80
  postgres:
    image: postgres:12.2
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - local-keycloak
  ### AUTHORIZATION -- KEYCLOAK ###
  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    image: jboss/keycloak
    ports: 
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
    restart: unless-stopped
    networks:
      - local-keycloak
  ### MICRO APPLICATIONS (MFE) ###
  mfe-php:
    container_name: php
    build:
       context: ./php
       dockerfile: ./DockerFile
    ports:
        - 8000:80
  mfe-react:
    container_name: react
    build:
       context: ./react
       dockerfile: ./DockerFile
    ports:
        - 8082:80
networks:
  local-keycloak:
