version: '3.4'
services:
  ### ROOT CONFIG CONTAINER -- SHELL ###
  root-config:
    container_name: root
    build:
        context: ./root-config
        dockerfile: ./DockerFile
    ports:
        - 8081:80
  ### AUTHENTICATION ###
  keycloak:
      container_name: keycloak
      image: jboss/keycloak
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: Password123!
      ports:
        - 8083:8080
  ### MICRO APPLICATIONS (MFE) ###
  mfe-php:
    container_name: php
    build:
       context: ./php
       dockerfile: ./DockerFile
    ports:
        - 8080:80
  mfe-react:
    container_name: react
    build:
       context: ./react
       dockerfile: ./DockerFile
    ports:
        - 8082:80
networks:
  default:
