version: '3.4'
services:
  ### ROOT CONFIG CONTAINER -- SHELL ###
  root-config:
    container_name: root
    build:
        context: ./root-config
        dockerfile: ./DockerFile
    ports:
        - 8081:80
  ### AUTHENTICATION ###
  auth-keycloak:
    container_name: keycloak
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8083:8080
  ### MICRO APPLICATIONS (MFE) ###
  mfe-php:
    container_name: php
    build:
       context: ./php
       dockerfile: ./DockerFile
    ports:
        - 8080:80
  mfe-react:
    container_name: react
    build:
       context: ./react
       dockerfile: ./DockerFile
    ports:
        - 8082:80
  ### DATABASE ###
  sql-database:
    container_name: sql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=Demo_Database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - 8084:3306
networks:
  default:
