FROM node:16 as build
WORKDIR /src/app
COPY . .
RUN npm install
RUN npm run build:webpack

FROM nginx:alpine
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /src/app/dist /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
